# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mysql.connector import Error
import mysql.connector as mc

class Ui_Dialog3(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(651, 424)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 300, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.register)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 20, 481, 51))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(110, 220, 481, 51))
        self.label1.setFont(font)
        self.label1.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(180, 120, 251, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 200, 251, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(180, 80, 251, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem('BCA')
        self.comboBox.addItem('BCOM')
        self.comboBox.addItem('BBA')
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 160, 251, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def register(self):
        rno = self.lineEdit.text()
        sname = self.lineEdit_3.text()
        year = self.lineEdit_2.text()
        course = self.comboBox.currentText()
        con=mc.connect(user='root',password='1864',host='localhost',port='3306',database='college')
        cur=con.cursor()
        query=("INSERT INTO CLASSROOM (sid,name,Department,year) VALUES (%s,%s,%s,%s)")
        insert_tuple=(int(rno),sname,course,int(year))
        cur.execute(query,insert_tuple)
        #self.label3 = Label(self,font='bold 10')
        self.label1.setText(str(cur.rowcount)+" row is inserted")
        #self.label3.config(text=str(cur.rowcount)+" row is inserted")
        #self.label3.place(x=280,y=360)
        con.commit()
        cur.close()
        con.close()
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Registration"))
        self.pushButton.setText(_translate("Dialog", "INSERT"))
        self.label.setText(_translate("Dialog", "REGISTER STUDENT INFORMATION OVER HERE"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "sid"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "year"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Name"))

def added():
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog3()
        ui.setupUi(Dialog)
        Dialog.show()
        sys.exit(app.exec_())
added()
