# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\FrontEnd\Attendence.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem,QHeaderView,QAbstractItemView,QPushButton,QTableWidget,QVBoxLayout,QHBoxLayout
from PyQt5.QtCore import Qt
import mysql.connector as mc
from mysql.connector import Error
from delete import Ui_Dialog2
from modify import Ui_Dialog1
from QR import Ui_Dialog4
from add import Ui_Dialog3
import delete 
import modify 
import QR
import add
class Ui_Form(object):
    def open_modify(self):
        self.Dialog1 = QtWidgets.QDialog()
        self.ui1 = Ui_Dialog1()
        self.ui1.setupUi(self.Dialog1)
        self.ui1.Database()
        self.ui1.option()
        self.Dialog1.show()
    def open_delete(self):
        self.Dialog2 = QtWidgets.QDialog()
        self.ui2 = Ui_Dialog2()
        self.ui2.setupUi(self.Dialog2)
        self.ui2.Database()
        self.Dialog2.show()
    def open_insert(self):
        self.Dialog3 = QtWidgets.QDialog()
        self.ui3 = Ui_Dialog3()
        self.ui3.setupUi(self.Dialog3)
        self.Dialog3.show()
    def open_Genrate(self):
        self.Dialog4 = QtWidgets.QDialog()
        self.ui4 = Ui_Dialog4()
        self.ui4.setupUi(self.Dialog4)
        self.Dialog4.show()
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1021, 609)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 290, 1001, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(789, 0, 231, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.open_insert)
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.open_delete)
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_6.clicked.connect(self.open_modify)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.open_Genrate)
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 771, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditDb = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditDb.setObjectName("lineEditDb")
        self.horizontalLayout.addWidget(self.lineEditDb)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 771, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_Tb = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_Tb.setObjectName("lineEdit_Tb")
        self.horizontalLayout_2.addWidget(self.lineEdit_Tb)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 200, 771, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.lineEdit_Search = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.horizontalLayout_3.addWidget(self.lineEdit_Search)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.search)
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.clear1)
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.showTable)
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.horizontalScrollBar = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(0, 580, 1021, 31))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(1000, 289, 23, 281))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.horizontalLayoutWidget_5)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_5.addWidget(self.verticalScrollBar)
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 170, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.Database)
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(130, 170, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.clear2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def Database(self):
        try:
            self.dbname = self.lineEditDb.text()
            self.tablename = self.lineEdit_Tb.text()
            self.conn = mc.connect(host="localhost",user="root",password="1864",database=self.dbname,port='3306')
            self.cur = self.conn.cursor(buffered=True)
            self.option()
        except Error as e:
            print(e)
        finally:
            print('Successfully connected')
    def showTable(self):
        self.cur.execute("select * from {};".format(self.tablename))
        results = self.cur.fetchall()
        self.tableWidget.setRowCount(0)
        for row_no , row_data in enumerate(results):
            self.tableWidget.insertRow(row_no)
            for col_no , data in enumerate(row_data):
                self.tableWidget.setItem(row_no,col_no,QTableWidgetItem(str(data)))
        
    def search(self):
        
        if self.lineEdit_Search.text() in ['none','None','null','NULL','Null','NONE']:
            self.cur.execute("select * from {} where {} is NULL;".format(self.tablename,self.comboBox.currentText()))
        elif self.comboBox.currentText() in ['sid','year']:
            s = self.lineEdit_Search.text()
            got = ("select * from {} where {} = {};".format(self.tablename,self.comboBox.currentText(),int(s)))
            self.cur.execute(got)
        elif self.comboBox.currentText() == 'attendence':
            a = self.lineEdit_Search.text()
            got = ("select * from {} where {} = '{}';".format(self.tablename,self.comboBox.currentText(),a.title()))
            self.cur.execute(got)
        elif self.comboBox.currentText() == 'Department':
            b = self.lineEdit_Search.text()
            got = ("select * from {} where {} = '{}';".format(self.tablename,self.comboBox.currentText(),b.upper()))
            self.cur.execute(got)
        elif self.comboBox.currentText() == 'name':
            c = self.lineEdit_Search.text()
            got = ("select * from {} where {} = '{}';".format(self.tablename,self.comboBox.currentText(),c.lower()))
            self.cur.execute(got)
        else:
            pass
        result = self.cur.fetchall()
        self.tableWidget.setRowCount(0)
        self.tableWidget.setHorizontalHeader(self.p)
        for row_no , row_data in enumerate(result):
            self.tableWidget.insertRow(row_no)
            for col_no , data in enumerate(row_data):
                self.tableWidget.setItem(row_no,col_no,QTableWidgetItem(str(data)))
    def option(self):
        self.cur.execute('select * from {}'.format(self.tablename))
        self.p = self.cur.column_names
        self.comboBox.addItems(self.p)
    def clear1(self):
        self.lineEdit_Search.clear()
    def clear2(self):
        self.lineEdit_Tb.clear()
        self.lineEditDb.clear()
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Attendence Management"))
        self.pushButton_5.setText(_translate("Form", "Add Student"))
        self.pushButton_4.setText(_translate("Form", "Remove Student"))
        self.pushButton_6.setText(_translate("Form", "Update"))
        self.pushButton_7.setText(_translate("Form", "Generate ID Card"))
        self.label.setText(_translate("Form", "Database Name"))
        self.label_2.setText(_translate("Form", "Table Name"))
        self.label_3.setText(_translate("Form", "Search By"))
        self.pushButton.setText(_translate("Form", "Search"))
        self.pushButton_2.setText(_translate("Form", "Clear"))
        self.pushButton_3.setText(_translate("Form", "Show all"))
        self.pushButton_8.setText(_translate("Form", "OK"))
        self.pushButton_9.setText(_translate("Form", "Clear"))

def dashboard():
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())
dashboard()
