# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\FrontEnd\deleteele.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mysql.connector import Error
import mysql.connector as mc

class Ui_Dialog2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 130, 191, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 60, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 170, 161, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.delete)
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def Database(self):
        try:
            self.conn = mc.connect(host="localhost",user="root",password="1864",database='college',port='3306')
            self.cur = self.conn.cursor(buffered=True)
        except Error as e:
            print(e)
        finally:
            print('Successfully connected')
    def delete(self):
        self.cur.execute("DELETE FROM classroom WHERE sid= {};".format(self.lineEdit.text()))
        print(self.cur.rowcount+"row is Deleted")
        self.conn.commit()
        self.cur.close()
        self.conn.close()
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Remove Student"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "sid"))
        self.label.setText(_translate("Dialog", "Delete element of Database"))
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Remove Student"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "sid"))
        self.label.setText(_translate("Dialog", "Delete element of Database"))
        self.pushButton.setText(_translate("Dialog", "Remove"))

def Remove():
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog2()
        ui.setupUi(Dialog)
        ui.Database( )
        Dialog.show()
        sys.exit(app.exec_())
Remove()
