# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import mysql.connector as mc
from mysql.connector import Error

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPainter, QPen 
from PyQt5.QtChart import QChart, QChartView, QPieSeries, QPieSlice
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QTableWidgetItem
import sys

class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1456, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1441, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 1441, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 1441, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(50)
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clear1)
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton")
        self.pushButton_3.clicked.connect(self.choosePieCombo)
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 520, 1441, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.clear)
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 550, 1441, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 790, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 790, 55, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)   
        self.count = 0
        self.count1 = 0
        self.comboBox.clear
         
    def Database(self):
        try:
            self.dbname = self.lineEdit.text()
            self.tablename = self.lineEdit_2.text()
            self.conn = mc.connect(host="localhost",user="root",password="1864",database=self.dbname,port='3306')
            self.cur = self.conn.cursor(buffered=True)
            self.cur.execute("select * from {};".format(self.tablename))
            results = self.cur.fetchall()
            self.tableWidget.setRowCount(0)
            for row_no , row_data in enumerate(results):
                self.tableWidget.insertRow(row_no)
                for col_no , data in enumerate(row_data):
                    self.tableWidget.setItem(row_no,col_no,QTableWidgetItem(str(data)))
            self.p = self.cur.column_names
            self.total = self.cur.rowcount
            self.comboBox.addItems(self.p)
            self.comboBox.addItem('All')
            self.comboBox.setCurrentText('All')
            self.label_6.setText(str(self.total))
            
            
            #self.option()
        except Error as e:
            print(e)
        finally:
            print('Successfully connected')      
        
    def create_piechart_3(self):
        a = self.abss
        b = self.press
        series = QPieSeries()
        series.append("Absent", a)
        series.append("Present", b)
        chart = QChart()
        chart.legend().hide()
        chart.addSeries(series)
        chart.createDefaultAxes()
        chart.setAnimationOptions(QChart.SeriesAnimations)
        chart.setTitle("Pie Chart of Attendence")
        chart.legend().setVisible(True)
        chart.legend().setAlignment(Qt.AlignBottom)
        chartview = QChartView(chart)
        chartview.setRenderHint(QPainter.Antialiasing)
        self.verticalLayout_2.addWidget(chartview)
    def clear(self):
        if self.conn.is_connected():
            while True:
                if self.count == 1:
                    break 
                self.count+=1
                self.var_present()
                self.create_piechart_3()
        else:
            pass
    def clear1(self):
        while True:
            if self.count1 == 1:
                break 
            self.count1+=1
            self.Database()
    def choosePieCombo(self):
        if self.comboBox.currentText() == 'All':
            self.cur.execute("select * from {};".format(self.tablename))
            results = self.cur.fetchall()
            self.tableWidget.setRowCount(0)
            for row_no , row_data in enumerate(results):
                self.tableWidget.insertRow(row_no)
                for col_no , data in enumerate(row_data):
                    self.tableWidget.setItem(row_no,col_no,QTableWidgetItem(str(data)))
        else:
            self.cur.execute("select {} from {};".format(self.comboBox.currentText(),self.tablename))
            results = self.cur.fetchall()
            self.tableWidget.setRowCount(0)
            for row_no , row_data in enumerate(results):
                self.tableWidget.insertRow(row_no)
                for col_no , data in enumerate(row_data):
                    self.tableWidget.setItem(row_no,col_no,QTableWidgetItem(str(data)))
    def var_present(self):
        self.cur.execute("select * from {} where attendence = 'Present';".format(self.tablename))
        self.press = self.cur.rowcount
        
        self.cur.execute("select * from {} where attendence = 'Absent';".format(self.tablename))
        self.abss = self.cur.rowcount
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DASHBOARD"))
        self.label.setText(_translate("MainWindow", "Database Name:"))
        self.label_2.setText(_translate("MainWindow", "Table Name:"))
        self.pushButton.setText(_translate("MainWindow", "Show all"))
        self.label_3.setText(_translate("MainWindow", "Charts"))
        self.pushButton_2.setText(_translate("MainWindow", "Show chart"))
        self.pushButton_3.setText(_translate("MainWindow", "Show "))
        self.label_4.setText(_translate("MainWindow", "Total No. Strength:"))
        
        self.label_6.setText(_translate("MainWindow","-"))
def Manage():        
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow1()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
Manage()
