# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\FrontEnd\update.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from mysql.connector import Error

class Ui_Dialog1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(651, 424)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 300, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.update)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 20, 481, 51))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(180, 80, 251, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 250, 251, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(180, 130, 251, 22))
        self.comboBox.setObjectName("comboBox")
        
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def Database(self):
        try:
            self.conn = mc.connect(host="localhost",user="root",password="1864",database='college',port='3306')
            self.cur = self.conn.cursor(buffered=True)
        except Error as e:
            print(e)
        finally:
            print('Successfully connected')
    def update(self):
        self.cur.execute("update classroom set {}='{}' WHERE sid={};".format(self.comboBox.currentText(),self.lineEdit_2.text(),int(self.lineEdit.text())))
        print(str(self.cur.rowcount)+"row is Modified")
        self.conn.commit()
        self.cur.close()
        self.conn.close()
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MODIFICATION"))
        self.pushButton.setText(_translate("Dialog", "UPDATE"))
        self.label.setText(_translate("Dialog", "UPDATE AND MODIFICATION of STUDENT INFO"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "sid"))
    def option(self):
        #self.cur.execute('select * from {}'.format(self.tablename))
        self.cur.execute('select * from classroom')
        self.p = self.cur.column_names
        self.comboBox.addItems(self.p)
def update():
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog1()
        ui.setupUi(Dialog)
        ui.Database()
        ui.option()
        Dialog.show()
        sys.exit(app.exec_())
update()