# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenerateQR.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from mysql.connector import Error
import qrcode as pq

class Ui_Dialog4(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(651, 424)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 300, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.GenrateQR)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 20, 131, 51))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(180, 120, 251, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit1.setGeometry(QtCore.QRect(180, 160, 251, 22))
        self.lineEdit1.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 200, 121, 20))
        self.label_2.setObjectName("label_2")
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def GenrateQR(self):
        b = self.lineEdit.text()
        candy = self.lineEdit1.text()
        print(candy)
        try:
            self.conn = mc.connect(host='localhost',database='college',user='root',password='1864',port='3306')
            if self.conn.is_connected():
                print('Connected to MySQL database')
            self.mycursor = self.conn.cursor()
            self.mycursor.execute("select name from classroom where sid = {};".format(int(b)))
            self.myresults = self.mycursor.fetchone()
            h = {39:None,40:None,41:None,44:None}
            a = str(self.myresults).translate(h)
            print(a)
            self.conn.commit()
            image = pq.make(a)
            image.save(f'{candy}\{a}.png')
            self.label_2.setText("QR is genrated")
            
            
        except Error as e:
            print(e)
        finally:
            print('Successfully connected ')
            self.mycursor.close()
            self.conn.close()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "QR Genrator"))
        self.pushButton.setText(_translate("Dialog", "GENERATE"))
        self.label.setText(_translate("Dialog", "GENERATE QR "))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "sid"))
        self.lineEdit1.setPlaceholderText(_translate("Dialog", "path"))

def QRgen():
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog4()
        ui.setupUi(Dialog)
        Dialog.show()
        sys.exit(app.exec_())
QRgen()